apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      name: {{ .Values.application.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: {{ .Values.application.name }}
        name: {{ .Values.application.name }}
    spec:
      containers:
        image: {{ printf "%s:%s" .Values.application.image .Values.application.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.application.name }}
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP